import { Hero } from './hero';

export const Heroes: Hero[] = [
  {
    id: 1001,
    name: 'Bandageman',
    imagePath: '../assets/bandageman.png',
    health: 100,
    power: 40,
    resistance: 50,
    race: 'human/undead',
    background:
      'A man who died in a fire was brought back to life by mysterious powers. The bandages keep his rotting body together and can be used as tools/weapons.',
    inDeck: false,
  },
  {
    id: 1002,
    name: 'Stronkman',
    imagePath: '../assets/stronkman.png',
    health: 100,
    power: 100,
    resistance: 100,
    race: 'human/brawler',
    background: 'A man with the strength to rip and tear dragon hide.',
    inDeck: false,
  },
  {
    id: 1003,
    name: 'Medic',
    imagePath: '../assets/dragon v7.jpg',
    health: 80,
    power: 40,
    resistance: 100,
    race: 'fairy/druid',
    background:
      "Most fairies heal their respective forests and the animal's within, this one heals every living creature in it's group",
    inDeck: false,
  },
  {
    id: 1004,
    name: 'Scout',
    imagePath: '../assets/character.png',
    health: 80,
    power: 20,
    resistance: 30,
    race: 'elf',
    background: 'An elf with high perception',
    inDeck: false,
  },
  {
    id: 1005,
    name: 'Assualt',
    imagePath: '../assets/hollow screamer vDarkness.jpg',
    health: 100,
    power: 40,
    resistance: 50,
    race: 'orc',
    background: 'Like the strong guy: strong but dumb.',
    inDeck: false,
  },
  {
    id: 1006,
    name: 'Support',
    imagePath: '../assets/anklebiter.png',
    health: 300,
    power: 50,
    resistance: 100,
    race: 'human/mage',
    background:
      'A mage is always useful, why look for a bridge if you can freeze over the lake!',
    inDeck: false,
  },
  {
    id: 1007,
    name: 'Shogun',
    imagePath: '../assets/TamoHelmet2BW320.png',
    health: 666,
    power: 666,
    resistance: 666,
    race: 'infernal',
    background: 'Infernals of the Underworld. The creatures of sin and sorrow.',
    inDeck: false,
  },
];
