import { Hero } from './hero';

export const Heroes: Hero[] = [
  {
    id: 1001,
    name: 'Fighter1',
    imagePath: '../assets/bandageman.png',
    health: 100,
    power: 40,
    resistance: 50,
    race: 'human/undead',
    background: '---Information here---',
    inDeck: false,
  },
  {
    id: 1002,
    name: 'Fighter2',
    imagePath: '../assets/TamoHelmet2BW320.png',
    health: 100,
    power: 100,
    resistance: 100,
    race: 'human/brawler',
    background: '---Information here---',
    inDeck: false,
  },
  {
    id: 1003,
    name: 'Medic1',
    imagePath: '../assets/dragon v7.jpg',
    health: 80,
    power: 40,
    resistance: 100,
    race: 'fairy/druid',
    background: '---Information here---',
    inDeck: false,
  },
  {
    id: 1004,
    name: 'Scout1',
    imagePath: '../assets/TamoHelmet2BW320.png',
    health: 80,
    power: 20,
    resistance: 30,
    race: 'elf',
    background: '---Information here---',
    inDeck: false,
  },
  {
    id: 1005,
    name: 'Fighter3',
    imagePath: '../assets/hollow screamer vDarkness.jpg',
    health: 100,
    power: 40,
    resistance: 50,
    race: 'orc',
    background: '---Information here---',
    inDeck: false,
  },
  {
    id: 1006,
    name: 'Fighter4',
    imagePath: '../assets/TamoHelmet2BW320.png',
    health: 300,
    power: 50,
    resistance: 100,
    race: 'human/mage',
    background: '---Information here---',
    inDeck: false,
  },
  {
    id: 1007,
    name: 'Oni',
    imagePath: '../assets/TamoHelmet2BW320.png',
    health: 666,
    power: 666,
    resistance: 666,
    race: 'infernal',
    background: '---Information here---',
    inDeck: false,
  },
];
